source 'https://rubygems.org'
gem 'sinatra'
#gem 'dm-sqlite-adapter'
#gem 'data_mapper'
gem 'json'
gem 'unicorn'
gem 'httparty'
#gem 'nokogiri'
#gem 'savon'
gem 'awesome_print'
gem "mongoid", "~> 2.4.6"
#gem 'mongoid'
gem 'mongo'
gem 'bson_ext'

